### ISSUE TITLE
How to make relative URLs

### ISSUE THREAD

**Issue by awokd** [Qubes-Community/Qubes-Community#3]
In https://github.com/Qubes-Community/Qubes-Community/blob/master/guides/hardware-tree.md for example, how can I convert to relative links?

**Comment by Aekez** [comment]
By relative links you mean inserting text/code from somewhere else right? i.e. somewhere else in the same shell/bash file? 

I found more than one of the answers in here very illuminating https://stackoverflow.com/questions/24112727/shell-relative-paths-based-on-file-location-instead-of-current-working-director I haven't gotten around to test it my self though, as this is also something I need to do in two of my current scripts, but still awaits to do. But it looks like it should work, and multiple approaches too.

**Comment by awokd** [comment]
I mean URLs. In qubes-doc I can link to `/doc/hcl` from inside another document instead of the full URL.

**Comment by Aekez** [comment]
aha, like that. Maybe it's the spaces? when formatting changes, i.e. from bash to shell, or to doc, html, different types of html, etc. then sometimes the langauge behaves a bit different right? So if you try remove the space between the ### and the headline, maybe it'll pick it up.

**Comment by awokd** [comment]
Solved in above linked issue.
