### ISSUE TITLE
github.io

### ISSUE THREAD

**Issue by awokd** [Qubes-Community/Qubes-Community#8]
@taradiddles suggested:

> how about setting up a diminutive github.io web landing page with statement, guides/instructions/... pointing to the project's github resources

[ EDIT / taradiddles: updating stuff in OP, I find it much easier to keep updates this way,+  people don't have to read all the comments to get the picture ]

---

There are two types of web sites: a global one for the organization, and one for each repository. It is possible to have both an organization page and per-repo pages.

For both types of pages:
* without an index.html file present, the site displays the content of the README.md file present at the url (on-the-fly markdown to html conversion).
* an index.html file takes precedence over the readme, its content is displayed as raw html (no conversion).  Note: I didn't find a way to link to a README.md file when an index.html file exists in the same folder.
* if the url file is a .md file, the url shouldn't include the .md suffix. Eg. https://qubes-community.github.io/Qubes-Community/guides/hardware-tree/ to read the hardware-tree.md file.
* there's no autogenerated index if neither a readme nor an index.html file exist at the url
* there's some caching on github's side, changes in files don't appear instantly after refreshing a page

#### Per-repo pages
doc: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

I've enabled web pages in the Qubes-Community repository (master branch). It's accessible at https://qubes-community.github.io/Qubes-Community/ (note: the part of the url after the hostname is case sensitive). Basically it's like a standard website:
* anyone can access subfolders, files, etc. - eg. https://qubes-community.github.io/Qubes-Community/scripts/qubes-auto-update-script-alpha.sh
* If the url is a subfolder without any file, either README.md or index.html is displayed (index.html takes precedence)
* there's no autogenerated index

#### Organization page
doc: https://help.github.com/articles/user-organization-and-project-pages/

I've created a `Qubes-Community.github.io` repo, the web page is accessible at https://qubes-community.github.io/

#### TBD

This whole web thing is quite flexible, so it's left to decide what to use (if we use that web feature at all, that is):

1. only a global site (actually, a single page) with links to various repos' **github** pages
    - with a basic README.md
    - or with a manually crafted index.html (prettier than the default github style, although I see there are some jekyll styles available for markdown)
2. same as 1- but with per-repo sites enabled, and the global page linking to **web** pages in the repositories. Cons: we loose page hierarchy because it's all "web" and the parent/child relationship has to be included manually in the readmes/html pages.

I am personally for 1. (either ways)

**Comment by awokd** [comment]
I'm not sure how to do this, do you know?

**Comment by Aekez** [comment]
@awokd try click on a repository, then go to settings, from there scroll down until you see "GitHub Pages " headline, near the bottom. I think each repository can have a page? but one should be sufficient though. You can also set the theme and such there. I'm not sure if a new repository should be made for this though, or if using the Qubes Community one. From how I understand it, you can make a separate branch, in the branch tab, which is used for the website files. I think that's how it maybe works in broad sense?

**Comment by taradiddles** [comment]
https://pages.github.com/

> Head over to GitHub and create a new repository named username.github.io, where username is your username (or organization name) on GitHub.

Looks like we have to create a `Qubes-Community.github.io` repo.

**Comment by awokd** [comment]
Thanks both, I think the first suggestion would work per repo but we'll need the second for a landing page type one. Want me to tackle it?

**Comment by taradiddles** [comment]
If you have time, go ahead. Otherwise I'll try to test it a bit later today.

btw I didn't know about the per-repo pages ; it could be an alternative to README.md-s, or an addition if the repo's content is large.

**Comment by Aekez** [comment]
@awokd no probs with me, it also seems you got some good ideas with it :)

good point, a landing page is important. I have no idea how the github.io repositories work though, but it's a very intriguing idea to make a website, and even more intriguing to make it this way through gihub, I'm looking forward to see it, although don't exhaust yourself either by doing too much. 

@taradiddles 
Do you think it can maybe be done on a pr. folder basis too? a bit like a normal website? For example maybe a repository can cover a whole website, but another repository can cover another website? but within each repository, it can be have sub-pages in different sub-folders? Taking a leap here, guessing, the page that is picked in the repository then must be the landing page?

**Comment by awokd** [comment]
Won't have much until the weekend, I'm afraid. Hope you don't mind me taking liberties with assigning it to you, at least for now!

**Comment by Aekez** [comment]
@awokd no worries from my part, whether today or later, it'll take the time it takes. I think @taradiddles might be busy too though? Imho it's fine with a long time perspective on this, especially considering it's volunteer stuff, it's not like we're getting paid on the hour or anything.

Let me know if I can help any of you with anything btw, I probably can't help with the advanced databases and such things, but I do have some basics in html/css/javascript.

**Comment by awokd** [comment]
Agreed, there's no deadlines. Just because there's a name on it doesn't mean others can't help. I figure most of the time people will self-assign.

**Comment by taradiddles** [comment]
no problem with the assignment.

I've created a `Qubes-Community.github.io` repo and `https://qubes-community.github.io/` is now active:

* without index.html file present, the site displays the content of the repo's README.md file (on-the-fly markdown to html conversion)
* an index.html file takes precedence over the readme, its content is displayed as raw html (no conversion).

So it's left to decide what to use (if we use that feature at all):
1. have a basic README.md pointing to the various repos' github pages or to their web pages (provided there's such a feature - haven't investigated that yet).
2. generate an index.html file automatically from README.md-s (or other files) in various repos/folders.
3. manually craft an index.html file ; but I'm not for that option, it's prone to error and will duplicate content from other pages/readmes.

**Comment by Aekez** [comment]
ohh, nice! It's starting to look interesting, though the whole mix with repositories does add some questions on how it would work in practice.

I'm a little worried if this github auto-generation of index files across repositories can reduce our degree of freedom/creativity to make the website, but I guess it won't be something that can't be solved with some work-arounds. 

Thoughts about adding a blog on the site some time further into the future? I.e. we can promote finished work that has a sufficient big enough size there (i.e. not small scripts or quick guides, but the larger ones). Maybe that could be made with an optional a-email sign-up subscription as well, so that everyone will know if something new is out, though optional of course. It might also not be a good idea in the beginning when everything is more slow, but once we get a bit further, a blog could help potentially help keeping the place more active. By the way, is this even possible on github hosting, do they allow complex scripts to run that make blogs work to be executed?

**Comment by taradiddles** [comment]
I've reorganized the post: I moved the content of my findings to the OP, I find it much easier to update its content this way, + other people who chime in later don't have to read the full thread to understand what we settle on.

@Aekez 
* no internal db = no internal advanced blog, but that doesn't prevent anyone from using a blog software/site, generate html files, and push them to the repo. This can be done automatically with machine keys.
* forget the automatic html generation - I proposed this idea before finding that it was possible to have both an organization site *and* per-repo sites / per-folder pages (the first doc I read seemed to imply it wasn't possible).

**Comment by awokd** [comment]
@Aekez can use the wiki for a blog. No need to over-complicate it if we can help it!

@taradiddles Nice, maybe that's how we can use relative links inside documents too? https://github.com/Qubes-Community/Qubes-Community/issues/3

**Comment by taradiddles** [comment]
re/ relative links:
* navigating a github page, a md file with a `[link](/relativepath)` link leads to the right page (see most of the links in Qubes-Community/README.md)
* on a web page autogenerated from the *same* md file, links are OK too (eg. https://qubes-community.github.io/Qubes-Community/ :  the links are relative in the html code).

btw I've updated the OP with new findings and TBD section

**Comment by awokd** [comment]
Thank you! OK to close this? We have a landing page, can propose edits as needed through PRs (right?)

**Comment by taradiddles** [comment]
Closing...

>can propose edits as needed through PRs

Sure ; or directly edit/commit to README.md in the Qubes-Community.github.io repo.

Just pay attention to link to github pages, not to "site" pages, otherwise page hierarchy/navigation is lost.

I have some important work that just popped up, I'll clean up my tests after I'm back.
